AllCops:
  NewCops: enable
  SuggestExtensions:
    rubocop-minitest: true
    rubocop-rake: true
    rubocop-rspec: false
  TargetRubyVersion: 2.6
  # Exclude directories
  Exclude:
    - 'cx_log.gemspec'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false


